# TRACER Framework - JSON Storage Only
version: '3.8'

services:
  tracer-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - STORAGE_TYPE=json
      - CORS_ORIGINS=${CORS_ORIGINS:-*}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - API_HOST=0.0.0.0
      - API_PORT=8000
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped